feat: Add support of confluence server.
kovetskiy/mark pull request #154
Opened 2022-01-17 17:56 UTC by vpommier

Add support of [personal access token authentication](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html) for confluence server.

2022-01-18 06:09 UTC, kovetskiy requested changes
I'm not sure it's a good way to break everyone's workflow and make them use some new flag which was not required before.

Can we just always send the Authorization token for both cloud and server?

2022-01-18 06:09 UTC, kovetskiy commented on main.go
> +	--confluence-cloud   Use Confluence Cloud or Confluence hosted server authentication method.
Something wrong with indentation here

2022-01-18 09:43 UTC, vpommier commented
> I'm not sure it's a good way to break everyone's workflow and make them use some new flag which was not required before.
> 
> Can we just always send the Authorization token for both cloud and server?

When i send the Authorization token it works only for server but not cloud.
And even if it worked there is no guarantee that this behavior (having basic auth + bearer token at the same time) will be supported in the future. It is the best way to attract issues in my opinion.

The thing that i can do is to require the new flag only for confluence server, in that way the new version will doesn't break the actual workflow.

I made these kind of changes to rapidly test if the tool can solve my issue with this authentication method. But i think the proper way to fix the code is to patch the code this way:
* [Headers should be copied instead of passing the reference of them `r.Headers.Clone()`. Because it create side effet.](https://github.com/kovetskiy/gopencils/blob/master/resource.go#L54)
* [Provide something more than just basic auth.](https://github.com/kovetskiy/gopencils/blob/master/api.go#L50)

2022-01-18 13:45 UTC, vpommier commented on main.go
> +	--confluence-cloud   Use Confluence Cloud or Confluence hosted server authentication method.
Fixed

2022-01-26 17:07 UTC, vpommier commented
Hi @kovetskiy i pushed modifications any news please ?

2022-02-02 10:01 UTC, kovetskiy commented
Works great, thanks!

2022-02-02 10:01 UTC, merged